export const ENV = {
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  isProduction: process.env.NODE_ENV === "production",
  llmProvider: process.env.LLM_PROVIDER ?? "",
  openaiApiKey: process.env.OPENAI_API_KEY ?? "",
  openaiChatModel: process.env.OPENAI_CHAT_MODEL ?? process.env.OPENAI_RESPONSES_MODEL ?? "",
  deepseekApiKey: process.env.DEEPSEEK_API_KEY ?? "",
  deepseekBaseUrl: process.env.DEEPSEEK_BASE_URL ?? "https://api.deepseek.com",
  deepseekModel: process.env.DEEPSEEK_MODEL ?? "deepseek-chat",
  snovioClientId: process.env.SNOVIO_CLIENT_ID ?? "",
  snovioClientSecret: process.env.SNOVIO_CLIENT_SECRET ?? "",
  googleClientId: process.env.GOOGLE_CLIENT_ID ?? "",
    googleClientSecret: process.env.GOOGLE_CLIENT_SECRET ?? "",
  // S3-compatible storage (Cloudflare R2 or AWS S3)
  s3Endpoint: process.env.S3_ENDPOINT ?? "",
  s3AccessKeyId: process.env.S3_ACCESS_KEY_ID ?? "",
  s3SecretAccessKey: process.env.S3_SECRET_ACCESS_KEY ?? "",
  s3Bucket: process.env.S3_BUCKET ?? "",
  s3PublicUrl: process.env.S3_PUBLIC_URL ?? "",
};
